apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
  namespace: expense
spec:
  selector:
    matchLabels:
      {{ toYaml .Values.commonLabels | nindent 4 }}    # has to match .spec.template.metadata.labels
  serviceName: "nginx-headless"
  replicas: {{ .Values.statefulset.replicas }} # by default is 1
  minReadySeconds: 10 # by default is 0
  template:
    metadata:
      labels:
        {{ toYaml .Values.commonLabels | nindent 4 }}   # has to match .spec.selector.matchLabels
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: mysql
        image: shahabsb/expense-mysql:{{ .Values.statefulset.version }}
        volumeMounts:
        - name: mysql
          mountPath: /var/lib/mysql
  # Instead of creating a PVC resource, you can directly provide in statefulset
  volumeClaimTemplates:
  - metadata:
      name: mysql
      namespace: expense
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "ebs-sc"
      resources:
        requests:
          storage: {{ .Values.statefulset.storage }}